language: python
dist: xenial
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "pypy"
  - "pypy3"
cache: pip
install:
  - pip install tox-travis
  - pip install -r requirements.txt
script:
  - flake8 . --ignore=E501,E402
  - tox
after_success:
  - coveralls
